version: '2'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_ID=1

  kafka:
    image: kafka:latest
    ports:
      - 9092:9092
    environment:
      - CONFIG_KAFKA_BROKER_ID=0
      - CONFIG_KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  collector:
    image: collector:latest
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
    environment:
      - BROKER_LIST=kafka:9092
      - MAX_CONTENT_LENGTH_KB=128
      - CONNECTION_LIMIT=32
      - CONNECTION_LIMIT_PER_IP=32
      - CONNECTION_TIMEOUT=4
      - COLLECTOR_CONFIG={"syscalls":["open","close","read","write","brk","execve","clone","procexit","socket","bind","connect","listen","accept","send","sendto","recv","recvfrom","shutdown","getsockname","setsockopt","getsockopt","sendmsg","recvmsg","pipe","chdir","mkdir","rmdir","openat","link","unlink","pread","pwrite","readv","writev","dup","kill","mmap","munmap","symlink","fork","vfork","procexit","setuid","setgid","getuid","getgid","seteuid","geteuid","setegid","getegid","chroot","init_module","finit_module"],"format":"1:container.id,2:evt.type,3:evt.time,4:evt.rawtime,5:evt.dir,6:container.image,7:container.name,9:evt.buflen,10:evt.category,11:evt.failed,12:evt.io_dir,13:evt.is_io,14:evt.is_io_read,15:evt.is_io_write,16:evt.rawres,17:evt.res,18:fd.cip,19:fd.cport,21:fd.directory,22:fd.filename,23:fd.ip,24:fd.is_server,26:fd.lip,27:fd.lport,29:fd.name,30:fd.port,32:fd.rip,33:fd.rport,35:fd.sip,36:fd.sockfamily,37:fd.sport,39:fd.type,40:fd.uid,41:group.gid,42:group.name,43:proc.args,44:proc.cmdline,45:proc.cwd,46:proc.exe,47:proc.exeline,48:proc.fdopencount,49:proc.name,50:proc.nchilds,51:proc.nthreads,52:proc.pname,53:proc.vmrss,54:proc.vmsize,55:proc.vmswap,56:thread.pfmajor,57:thread.pfminor,58:user.homedir,59:user.name,60:user.shell,61:user.uid,62:evt.args,63:evt.buffer,64:thread.vtid","output":"kafka","defaultTopic":"topic-default"}
    depends_on:
      - kafka
